---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager-localmode
  namespace: mongodb
spec:
  replicas: 2
  version: 4.2.6  # the version of Ops Manager 

  # the name of the secret containing admin user credentials.
  adminCredentials: ops-manager-admin-secret

  configuration:
    mms.ignoreInitialUiSetup: "true"
    mms.fromEmailAddr:  "test@test.com"
    mms.adminEmailAddr: "test@test.com"
    mms.replyToEmailAddr:  "test@test.com"
    mms.mail.hostname: "localhost"
    mms.mail.transport: "smtps"
    mms.security.allowCORS: "false"
    mms.minimumTLSVersion: TLSv1.2
    mms.mail.port: "465"


  statefulSet:
    spec:
      # the Persistent Volume Claim will be created for each Ops Manager Pod
      volumeClaimTemplates:
        - metadata:
            name: mongodb-versions
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 10G
      template:
        spec:
          containers:
            - name: mongodb-ops-manager
              volumeMounts:
                - name: mongodb-versions
                  # this is the directory in each Pod where all MongoDB
                  # archives must be put
                  mountPath: /mongodb-ops-manager/mongodb-releases


  externalConnectivity:
   type: LoadBalancer


  applicationDatabase:
    passwordSecretKeyRef:
      name: om-db-user-secret
      key: password
    members: 3
    version: 4.2.12-ent
    persistent: true
