apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager-localmode
  namespace: mongodb
spec:
  replicas: 1
  version: 4.2.6  # the version of Ops Manager 

  # the name of the secret containing admin user credentials.
  adminCredentials: ops-manager-admin-secret

  configuration:
    mms.ignoreInitialUiSetup: "true"
    mms.fromEmailAddr:  "test@test.com"
    mms.adminEmailAddr: "test@test.com"
    mms.replyToEmailAddr:  "test@test.com"
    mms.mail.hostname: "localhost"
    mms.mail.transport: "smtps"
    mms.security.allowCORS: "false"
    mms.minimumTLSVersion: TLSv1.2
    mms.mail.port: "465"


  externalConnectivity:
   type: LoadBalancer


  applicationDatabase:
    passwordSecretKeyRef:
      name: om-db-user-secret
      key: password
    members: 3
    version: 4.2.12-ent
    persistent: true
